# This workflow is only intended to run when a pull-request is merged into the main branch
name: Main branch Workflow

on:
  push:
    branches: [main]

jobs:
  run_pipeline:
    name: Build System Artifacts
    uses: ./.github/workflows/pull-requests.yml
